---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - virtualmachine.yaml

patches:
  - target:
      group: kubevirt.io
      kind: VirtualMachine
      name: .*
      version: v1
    patch: |-
      - op: replace
        path: /spec/runStrategy
        value: RerunOnFailure